project:
  title: "PHI 205"
  type: website

website:
  title: "PHI 205"
  description: "Course webpage for PHI 205 at Illinois State"
  site-url: "https://www.davidsanson.com/205f2026"
  repo-url: https://github.com/dsanson/205f2026
  repo-actions: [source, issue]
  favicon: media/favicon.png
  twitter-card: true
  open-graph: true
  page-footer: |
    © 2026 David Sanson. Created using [Quarto](https://quarto.org/).
  navbar:
    logo: media/favicon.png
    logo-alt: 'Φ'
    left:
      - href: index.md
        text: Home
      - href: syllabus.md
        text: Syllabus
      - href: schedule.md
        text: Schedule

bibliography: [references.json]
citeproc: true
filters:
  - label-bullets.lua

metadata:
  author:
  - name: David Sanson
  course: PHI 205

callout-appearance: minimal

format:
  html:
    axe: true
    toc: true
    respect-user-color-scheme: true
    template-partials:
      - title-metadata.html
    theme:
      light: 
        - flatly
        - theme-light.scss
        - custom.scss
      dark: 
        - darkly
        - custom.scss
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true

    format-links:
    - html
    - format: typst
      icon: file-pdf
      text: PDF

  # pdf:
  #   pdf-standard: [ ua-2 ]
        
  typst:
    citeproc: true
    template-partials:
    - typst-template.typ
    fontsize: 10pt
    mainfont: "libertinus serif"
    sansfont: "libertinus sans"
    margin:
      x: 1in
      y: 1in
    papersize: us-letter
    #pdf-standard: [ ua-1 ]
